test_p1 (__main__.Test.test_p1) ... FAIL
test_p10 (__main__.Test.test_p10) ... ERROR
test_p2 (__main__.Test.test_p2) ... ok
test_p3 (__main__.Test.test_p3) ... ERROR
test_p4 (__main__.Test.test_p4) ... ERROR
test_p5 (__main__.Test.test_p5) ... ok
test_p6 (__main__.Test.test_p6) ... ok
test_p7 (__main__.Test.test_p7) ... ERROR
test_p8 (__main__.Test.test_p8) ... ok
test_p9 (__main__.Test.test_p9) ... ok

======================================================================
ERROR: test_p10 (__main__.Test.test_p10)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\Podstawy programowania\prg-basics\06-Test1\grade-test1-ZIISS1-1112.py", line 66, in test_p10
    import p10
ModuleNotFoundError: No module named 'p10'

======================================================================
ERROR: test_p3 (__main__.Test.test_p3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\Podstawy programowania\prg-basics\06-Test1\grade-test1-ZIISS1-1112.py", line 24, in test_p3
    import p3
ModuleNotFoundError: No module named 'p3'

======================================================================
ERROR: test_p4 (__main__.Test.test_p4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\Podstawy programowania\prg-basics\06-Test1\grade-test1-ZIISS1-1112.py", line 31, in test_p4
    import p4
ModuleNotFoundError: No module named 'p4'

======================================================================
ERROR: test_p7 (__main__.Test.test_p7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\Podstawy programowania\prg-basics\06-Test1\grade-test1-ZIISS1-1112.py", line 48, in test_p7
    import p7
ModuleNotFoundError: No module named 'p7'

======================================================================
FAIL: test_p1 (__main__.Test.test_p1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\Podstawy programowania\prg-basics\06-Test1\grade-test1-ZIISS1-1112.py", line 15, in test_p1
    self.assertEqual(p1.f(174,62),"0x32")
AssertionError: '0x1' != '0x32'
- 0x1
+ 0x32


----------------------------------------------------------------------
Ran 10 tests in 0.012s

FAILED (failures=1, errors=4)
